image: registry.gitlab.com/maketechpub/docker/alpine:jdk8.mvn

stages:
  - build

build.p2:
  stage: build
  script:
    - mvn -B -nsu package
    - mvn -B -nsu site:site -Dgithub.global.userName=${GITHUB_USER} -Dgithub.global.password=${GITHUB_PASS}
  only: 
    - master